baseurl = "https://0x7e3.hackmeeting.org.bo/"
title = "HACKMEETING 0x7e3"
theme = "hackmeeting-hugo"
languageCode = "es"
preserveTaxonomyNames = true
enableEmoji = true

[params]
  # Unmark to use post folder for images. Default is static folder.
  #usepostimgfolder = true
  slogan = "20, 21 y 22 de septiembre (La Paz, BO)"
  description = "Evento libre y abierto para comunidades hacker de todas partes."
  copyright = [
    "(ↄ) 2019 Comisión Hackmeeting 0x7e3 La Paz",
  ]


  [[menu.main]]
  name = "Inicio"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Información"
  url = "info/"
  weight = 2

  [[menu.main]]
  name = "Cómo llegar"
  url = "ubicacion/"
  weight = 3

  [[menu.main]]
  name = "Charlas"
  url = "charlas/"
  weight = 4

  [[menu.main]]
  name = "En vivo"
  url = "envivo/"
  weight = 5

  #[[menu.main]]
  #name = "Quiero Participar"
  #url = "participar/"
  #weight = 5

  [[menu.main]]
  name = "Contacto"
  url = "contacto/"
  weight = 6

  [[menu.main]]
  name = "Memorias"
  url = "https://memorias.hackmeeting.org.bo/"
  weight = 7

